{
 "title": "Court Backend",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": "label_values({job=~\"(.*/)?court-backend(-.*)?\"}, service)"
   }
  ]
 },
 "panels": [
  { "title": "Server and Services up status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Server",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (service) (up{service=\"$service\",endpoint=\"server-metrics\"})",
     "legendFormat": "$endpoint"
    }
   ]
  },
  {
   "title": "Heartbeat",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (service) (up{service=\"$service\",endpoint=\"metrics-hbeat\"})",
     "legendFormat": "$endpoint"
    }
   ]
  },
  {
   "title": "Reveal",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (service) (up{service=\"$service\",endpoint=\"metrics-reveal\"})",
     "legendFormat": "$endpoint"
    }
   ]
  },
  {
   "title": "Settlements",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (service) (up{service=\"$service\",endpoint=\"metrics-settle\"})",
     "legendFormat": "$endpoint"
    }
   ]
  },
  {
   "title": "Monitor Keeper",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (service) (up{service=\"$service\",endpoint=\"metrics-keeper\"})",
     "legendFormat": "$endpoint"
    }
   ]
  },
  {
   "title": "Notification Scanner",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (service) (up{service=\"$service\",endpoint=\"metrics-scanner\"})",
     "legendFormat": "$endpoint"
    }
   ]
  },
  {
   "title": "Notification Sender",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (service) (up{service=\"$service\",endpoint=\"metrics-sender\"})",
     "legendFormat": "$endpoint"
    }
   ]
  },
  { "title": "Server Metrics and Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Server status codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status_code) (rate(http_requests_total{service=\"$service\"}[5m]))",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Server 4** by path",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (path) (irate(http_requests_total{service=\"$service\",status_code=~\"4.*\"}[5m]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Server logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "{app=\"$service\",container_name=~\".*server.*\"}"
    }
   ]
  },
  {
   "title": "Server 5** by path",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (path) (irate(http_requests_total{service=\"$service\",status_code=~\"5.*\"}[5m]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  { "title": "Services Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Service worker successful runs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (workerName) (rate(worker_success{service=\"$service\"}[30m]))",
     "legendFormat": "{{workerName}}"
    }
   ]
  },
  {
   "title": "Notification scan runs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (scannerName) (rate(notifications_scanned{service=\"$service\"}[30m]))",
     "legendFormat": "{{scannerName}}"
    }
   ]
  },
  {
   "title": "Service worker errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (workerName) (irate(worker_errors{service=\"$service\"}[5m]))",
     "legendFormat": "{{workerName}}"
    }
   ]
  },
  {
   "title": "Notification emails sent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (scannerName) (rate(notifications_sent{service=\"$service\"}[30m]))",
     "legendFormat": "{{scannerName}}"
    }
   ]
  },
  { "title": "Services Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Heartbeats",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "{app=\"$service\",container_name=~\".*services.*\"}|=\"[heartbeat]\""
    }
   ]
  },
  {
   "title": "Reveals",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "{app=\"$service\",container_name=~\".*services.*\"}|=\"[reveal]\""
    }
   ]
  },
  {
   "title": "Settlements",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "{app=\"$service\",container_name=~\".*services.*\"}|=\"[settlements]\""
    }
   ]
  },
  {
   "title": "Monitor keeper",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "{app=\"$service\",container_name=~\".*services.*\"}|=\"[monitor-keeper]\""
    }
   ]
  },
  {
   "title": "Notification scanner",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "{app=\"$service\",container_name=~\".*services.*\"}|=\"[notification-scanner]\""
    }
   ]
  },
  {
   "title": "Notification sender",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "{app=\"$service\",container_name=~\".*services.*\"}|=\"[notification-sender]\""
    }
   ]
  },
  {
   "title": "RPC calls",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "{app=\"$service\",container_name=~\".*services.*\"}|=\"[Provider]\""
    }
   ]
  },
  {
   "title": "All service logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "{app=\"$service\",container_name=~\".*services.*\"}"
    }
   ]
  },
  { "title": "Backoffice logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Backoffice logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "{app=\"$service\",container_name=~\".*(app|backoffice).*\"}"
    }
   ]
  }
 ]
}