export const SHOW_ERROR = 'SHOW_ERROR'
export const RESET_ERROR = 'RESET_ERROR'
export const STOP_FETCHING = 'STOP_FETCHING'
export const START_FETCHING = 'START_FETCHING'

export const RECEIVE_ACCOUNT = 'RECEIVE_ACCOUNT'
export const RECEIVE_ETH_BALANCE = 'RECEIVE_ETH_BALANCE'
export const RECEIVE_ANJ_BALANCE = 'RECEIVE_ANJ_BALANCE'
export const RECEIVE_ANT_BALANCE = 'RECEIVE_ANT_BALANCE'
export const RECEIVE_FEE_BALANCE = 'RECEIVE_FEE_BALANCE'
export const RECEIVE_WEB3_ENABLED = 'RECEIVE_WEB3_ENABLED'

export const RECEIVE_FAUCET = 'RECEIVE_FAUCET'
export const RECEIVE_FAUCET_ANT_BALANCE = 'RECEIVE_FAUCET_ANT_BALANCE'
export const RECEIVE_FAUCET_ANJ_BALANCE = 'RECEIVE_FAUCET_ANJ_BALANCE'
export const RECEIVE_FAUCET_FEE_BALANCE = 'RECEIVE_FAUCET_FEE_BALANCE'

export const RECEIVE_COURT_CONFIG = 'RECEIVE_COURT_CONFIG'

export const RECEIVE_DISPUTE = 'RECEIVE_DISPUTE'
export const RECEIVE_DISPUTES_LIST = 'RECEIVE_DISPUTES_LIST'

export const RECEIVE_JUROR = 'RECEIVE_JUROR'
export const RECEIVE_JURORS_LIST = 'RECEIVE_JURORS_LIST'
export const RECEIVE_JUROR_DRAFTS = 'RECEIVE_JUROR_DRAFTS'
export const RECEIVE_JUROR_ACCOUNTING = 'RECEIVE_JUROR_ACCOUNTING'

export const RECEIVE_DRAFT = 'RECEIVE_DRAFT'
export const RECEIVE_DRAFTS_LIST = 'RECEIVE_DRAFTS_LIST'

export const RECEIVE_TRANSFERS = 'RECEIVE_TRANSFERS'
export const RECEIVE_BALANCES = 'RECEIVE_BALANCES'

export const RECEIVE_ADMIN = 'RECEIVE_ADMIN'
export const RESET_ADMIN = 'RESET_ADMIN'
export const RECEIVE_ADMIN_TOKEN = 'RECEIVE_ADMIN_TOKEN'
export const RESET_ADMIN_TOKEN = 'RESET_ADMIN_TOKEN'
export const RECEIVE_ADMIN_ADMINS = 'RECEIVE_ADMIN_ADMINS'
export const RECEIVE_ADMIN_REVEALS = 'RECEIVE_ADMIN_REVEALS'
export const RECEIVE_ADMIN_SETTLEMENTS = 'RECEIVE_ADMIN_SETTLEMENTS'
export const RECEIVE_ADMIN_ERRORS = 'RECEIVE_ADMIN_ERRORS'
export const RECEIVE_ADMIN_ERROR = 'RECEIVE_ADMIN_ERROR'
