export const SHOW_ERROR = 'SHOW_ERROR'
export const RESET_ERROR = 'RESET_ERROR'
export const STOP_FETCHING = 'STOP_FETCHING'
export const START_FETCHING = 'START_FETCHING'

export const RECEIVE_ACCOUNT = 'RECEIVE_ACCOUNT'
export const RECEIVE_ETH_BALANCE = 'RECEIVE_ETH_BALANCE'
export const RECEIVE_ANJ_BALANCE = 'RECEIVE_ANJ_BALANCE'
export const RECEIVE_FEE_BALANCE = 'RECEIVE_FEE_BALANCE'

export const RECEIVE_DISPUTE = 'RECEIVE_DISPUTE'
export const RECEIVE_DISPUTES_LIST = 'RECEIVE_DISPUTES_LIST'

export const RECEIVE_TRANSFERS = 'RECEIVE_TRANSFERS'
export const RECEIVE_BALANCES = 'RECEIVE_BALANCES'
