name: Email templates/assets sync
on:
  push:
    branches:
    - development
    paths:
    - 'emails/**'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        project_id: ${{secrets.GCP_PROJECT_ID}}
        service_account_key: ${{secrets.GCP_SA_KEY}}
        export_default_credentials: true
    - run: .github/scripts/emails-sync.sh ${{secrets.POSTMARK_SERVER_API_TOKEN_STAGING}}
