name: Testnet CI/CD
on:
  push:
    branches:
    # Executes on any non master commit, but release and deploy steps only run on development
    # This is useful to see if tests are passing during PR review
    - '**'
    - '!master'
    paths-ignore:
    - 'monitoring/**'
    - 'emails/**'
env:
  # This is a base repository and we use ${GITHUB_SHA} to set the version of the container
  REPO: docker.pkg.github.com/aragonone/court-backend/testnet

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p ${{secrets.GITHUB_TOKEN}}
    - run: .github/scripts/docker-build.sh $REPO ${GITHUB_SHA}

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p ${{secrets.GITHUB_TOKEN}}
    - run: .github/scripts/test/run.sh $REPO:${GITHUB_SHA}

  release:
    if: github.ref == 'refs/heads/development'
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v2
    - run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p ${{secrets.GITHUB_TOKEN}}
    - run: .github/scripts/docker-release.sh $REPO:${GITHUB_SHA} $REPO:latest

  deploy:
    if: github.ref == 'refs/heads/development'
    runs-on: ubuntu-latest
    needs: release
    steps:
    - uses: actions/checkout@v2
    - run: .github/scripts/kubectl-config.sh ${{secrets.KUBE_CA}} ${{secrets.KUBE_SERVER}} ${{secrets.KUBE_TOKEN}}
    - run: .github/scripts/kubectl-set-image.sh court-backend-rinkeby $REPO:${GITHUB_SHA}
    - run: .github/scripts/kubectl-set-image.sh court-backend-staging $REPO:${GITHUB_SHA}
    - run: .github/scripts/kubectl-set-image.sh court-backend-ropsten $REPO:${GITHUB_SHA}
    - run: .github/scripts/kubectl-wait-ready.sh court-backend-rinkeby
    - run: .github/scripts/kubectl-wait-ready.sh court-backend-staging
    - run: .github/scripts/kubectl-wait-ready.sh court-backend-ropsten
    # wait 10 sec for k8s to reroute ingress and check app endpoint
    - run: sleep 10 && curl --fail https://court-backend-app-rinkeby.eth.aragon.network
    - run: curl --fail https://court-backend-app-staging.eth.aragon.network
    - run: curl --fail https://court-backend-app-ropsten.eth.aragon.network
